version: '3'

services:
  database:
    image: mysql:5.7.28
    hostname: swgemu_database
    container_name: swgemu_database_standalone
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=swgemuroot
      - MYSQL_DATABASE=swgemu
      - MYSQL_USER=swgemu
      - MYSQL_PASSWORD=swgemu-sql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    restart: always